# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Codes\PyQt5Projects\blogui\Index.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormMainWindow(object):
    def setupUi(self, FormMainWindow):
        FormMainWindow.setObjectName("FormMainWindow")
        FormMainWindow.resize(502, 391)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormMainWindow)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetMain = QtWidgets.QWidget(FormMainWindow)
        self.widgetMain.setObjectName("widgetMain")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetMain)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetTitleBar = QtWidgets.QWidget(self.widgetMain)
        self.widgetTitleBar.setObjectName("widgetTitleBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetTitleBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(119, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonSkin = QtWidgets.QPushButton(self.widgetTitleBar)
        self.buttonSkin.setText("")
        self.buttonSkin.setObjectName("buttonSkin")
        self.horizontalLayout_3.addWidget(self.buttonSkin)
        self.buttonMinimum = QtWidgets.QPushButton(self.widgetTitleBar)
        self.buttonMinimum.setText("")
        self.buttonMinimum.setObjectName("buttonMinimum")
        self.horizontalLayout_3.addWidget(self.buttonMinimum)
        self.buttonMaximum = QtWidgets.QPushButton(self.widgetTitleBar)
        self.buttonMaximum.setText("")
        self.buttonMaximum.setObjectName("buttonMaximum")
        self.horizontalLayout_3.addWidget(self.buttonMaximum)
        self.buttonNormal = QtWidgets.QPushButton(self.widgetTitleBar)
        self.buttonNormal.setText("")
        self.buttonNormal.setObjectName("buttonNormal")
        self.horizontalLayout_3.addWidget(self.buttonNormal)
        self.buttonClose = QtWidgets.QPushButton(self.widgetTitleBar)
        self.buttonClose.setText("")
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout_3.addWidget(self.buttonClose)
        self.verticalLayout.addWidget(self.widgetTitleBar)
        self.widgetCenter = QtWidgets.QWidget(self.widgetMain)
        self.widgetCenter.setObjectName("widgetCenter")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetCenter)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widgetCatalogs = QtWidgets.QWidget(self.widgetCenter)
        self.widgetCatalogs.setMinimumSize(QtCore.QSize(100, 0))
        self.widgetCatalogs.setObjectName("widgetCatalogs")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetCatalogs)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetHeader = QtWidgets.QWidget(self.widgetCatalogs)
        self.widgetHeader.setObjectName("widgetHeader")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widgetHeader)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.widgetHeader)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.widgetHeader)
        self.widgetSearch = QtWidgets.QWidget(self.widgetCatalogs)
        self.widgetSearch.setObjectName("widgetSearch")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetSearch)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widgetSearch)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widgetSearch)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.widgetSearch)
        self.treeView = QtWidgets.QTreeView(self.widgetCatalogs)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_3.addWidget(self.treeView)
        self.horizontalLayout_4.addWidget(self.widgetCatalogs)
        self.widgetTools = QtWidgets.QWidget(self.widgetCenter)
        self.widgetTools.setObjectName("widgetTools")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widgetTools)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.widgetTools)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.widgetTools)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widgetTools)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.widgetTools)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(self.widgetTools)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout_4.addWidget(self.widgetTools)
        self.widgetContents = QtWidgets.QWidget(self.widgetCenter)
        self.widgetContents.setObjectName("widgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.widgetContents)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.webviewContents = QtWidgets.QWidget(self.widgetContents)
        self.webviewContents.setObjectName("webviewContents")
        self.verticalLayout_2.addWidget(self.webviewContents)
        self.horizontalLayout_4.addWidget(self.widgetContents)
        self.verticalLayout.addWidget(self.widgetCenter)
        self.horizontalLayout.addWidget(self.widgetMain)

        self.retranslateUi(FormMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FormMainWindow)

    def retranslateUi(self, FormMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FormMainWindow.setWindowTitle(_translate("FormMainWindow", "PyQt5Client"))
        self.label.setText(_translate("FormMainWindow", "TextLabel"))
        self.pushButton.setText(_translate("FormMainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("FormMainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("FormMainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("FormMainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("FormMainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("FormMainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMainWindow = QtWidgets.QWidget()
    ui = Ui_FormMainWindow()
    ui.setupUi(FormMainWindow)
    FormMainWindow.show()
    sys.exit(app.exec_())

