# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\codes\PyQt5Projects\blogui\SkinDialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SkinDialog(object):
    def setupUi(self, SkinDialog):
        SkinDialog.setObjectName("SkinDialog")
        SkinDialog.resize(477, 344)
        SkinDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SkinDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(SkinDialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogTitleBar = QtWidgets.QWidget(self.widget)
        self.dialogTitleBar.setObjectName("dialogTitleBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogTitleBar)
        self.horizontalLayout.setContentsMargins(0, 1, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(self.dialogTitleBar)
        self.labelTitle.setIndent(6)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(408, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonClose = QtWidgets.QPushButton(self.dialogTitleBar)
        self.buttonClose.setText("")
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayout.addWidget(self.buttonClose)
        self.verticalLayout_2.addWidget(self.dialogTitleBar)
        self.widgetSkinBg = QtWidgets.QWidget(self.widget)
        self.widgetSkinBg.setObjectName("widgetSkinBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widgetSkinBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidgetSkinMain = QtWidgets.QTabWidget(self.widgetSkinBg)
        self.tabWidgetSkinMain.setObjectName("tabWidgetSkinMain")
        self.tabTheme = QtWidgets.QWidget()
        self.tabTheme.setObjectName("tabTheme")
        self.tabWidgetSkinMain.addTab(self.tabTheme, "")
        self.tabColourful = QtWidgets.QWidget()
        self.tabColourful.setObjectName("tabColourful")
        self.tabWidgetSkinMain.addTab(self.tabColourful, "")
        self.tabPicture = QtWidgets.QWidget()
        self.tabPicture.setObjectName("tabPicture")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabPicture)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.tabPicture)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(30, 10, 30, 10)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widgetCategories = QtWidgets.QWidget(self.widget_2)
        self.widgetCategories.setObjectName("widgetCategories")
        self.verticalLayout_5.addWidget(self.widgetCategories)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.stackedWidgetPictures = QtWidgets.QStackedWidget(self.tabPicture)
        self.stackedWidgetPictures.setObjectName("stackedWidgetPictures")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidgetPictures.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidgetPictures.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidgetPictures)
        self.tabWidgetSkinMain.addTab(self.tabPicture, "")
        self.verticalLayout_3.addWidget(self.tabWidgetSkinMain)
        self.widgetBottom = QtWidgets.QWidget(self.widgetSkinBg)
        self.widgetBottom.setMinimumSize(QtCore.QSize(0, 64))
        self.widgetBottom.setObjectName("widgetBottom")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetBottom)
        self.horizontalLayout_2.setContentsMargins(30, 0, 30, 0)
        self.horizontalLayout_2.setSpacing(14)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widgetBottom)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.sliderOpacity = QtWidgets.QSlider(self.widgetBottom)
        self.sliderOpacity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sliderOpacity.setMaximum(100)
        self.sliderOpacity.setPageStep(1)
        self.sliderOpacity.setProperty("value", 100)
        self.sliderOpacity.setSliderPosition(100)
        self.sliderOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOpacity.setInvertedAppearance(True)
        self.sliderOpacity.setInvertedControls(False)
        self.sliderOpacity.setObjectName("sliderOpacity")
        self.horizontalLayout_2.addWidget(self.sliderOpacity)
        spacerItem1 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.buttonRestore = QtWidgets.QPushButton(self.widgetBottom)
        self.buttonRestore.setObjectName("buttonRestore")
        self.horizontalLayout_2.addWidget(self.buttonRestore)
        self.verticalLayout_3.addWidget(self.widgetBottom)
        self.verticalLayout_2.addWidget(self.widgetSkinBg)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(SkinDialog)
        self.tabWidgetSkinMain.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(SkinDialog)

    def retranslateUi(self, SkinDialog):
        _translate = QtCore.QCoreApplication.translate
        SkinDialog.setWindowTitle(_translate("SkinDialog", "Dialog"))
        self.labelTitle.setText(_translate("SkinDialog", "skin"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabTheme), _translate("SkinDialog", "Theme"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabColourful), _translate("SkinDialog", "Colourful"))
        self.tabWidgetSkinMain.setTabText(self.tabWidgetSkinMain.indexOf(self.tabPicture), _translate("SkinDialog", "Picture"))
        self.label.setText(_translate("SkinDialog", "Transparency"))
        self.buttonRestore.setText(_translate("SkinDialog", "Restore the default theme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SkinDialog = QtWidgets.QDialog()
    ui = Ui_SkinDialog()
    ui.setupUi(SkinDialog)
    SkinDialog.show()
    sys.exit(app.exec_())

