"""empty message

Revision ID: 3d6a68b6f4f3
Revises: 6b58d7b63976
Create Date: 2021-04-09 14:25:19.258256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6a68b6f4f3'
down_revision = '6b58d7b63976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'address', 'customer', ['a_customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    # ### end Alembic commands ###
