"""empty message

Revision ID: 47bc2eb2ee6e
Revises: 119e3ac2e1cf
Create Date: 2021-04-08 11:27:04.268668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47bc2eb2ee6e'
down_revision = '119e3ac2e1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('c_eat', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('a_name', sa.String(length=32), nullable=True),
    sa.Column('d_legs', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('a_name')
    )
    op.drop_index('a_name', table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('a_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('d_legs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('c_eat', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('a_name', 'animals', ['a_name'], unique=True)
    op.drop_table('dogs')
    op.drop_table('cats')
    # ### end Alembic commands ###
