"""empty message

Revision ID: 554f5d3ea258
Revises: 184ab2b04dff
Create Date: 2021-04-07 10:43:20.297150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '554f5d3ea258'
down_revision = '184ab2b04dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('u_des', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('u_name', sa.String(length=22), nullable=True))
    op.create_unique_constraint(None, 'users', ['u_name'])
    op.drop_column('users', 'gender')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=22), nullable=True))
    op.add_column('users', sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'u_name')
    op.drop_column('users', 'u_des')
    # ### end Alembic commands ###
